/**
 * Pre-built Theme Library
 * Professionally designed themes that meet WCAG AA standards
 */

export interface ThemeDefinition {
  name: string;
  description: string;
  colors: Record<string, string>;
  category: "dark" | "light" | "colorful" | "minimal" | "accessibility";
  tags: string[];
}

export const DEFAULT_THEMES: ThemeDefinition[] = [
  {
    name: "Default Dark",
    description: "The classic Terminus dark theme",
    category: "dark",
    tags: ["dark", "default", "professional"],
    colors: {
      "--background": "#0a0a0a",
      "--foreground": "#ededed",
      "--card": "#0a0a0a",
      "--card-foreground": "#ededed",
      "--popover": "#0a0a0a",
      "--popover-foreground": "#ededed",
      "--primary": "#ededed",
      "--primary-foreground": "#0a0a0a",
      "--secondary": "#1a1a1a",
      "--secondary-foreground": "#ededed",
      "--muted": "#1a1a1a",
      "--muted-foreground": "#a1a1aa",
      "--accent": "#1a1a1a",
      "--accent-foreground": "#ededed",
      "--destructive": "#7f1d1d",
      "--destructive-foreground": "#ededed",
      "--border": "#1a1a1a",
      "--input": "#1a1a1a",
      "--ring": "#d4d4d8",
    },
  },
  {
    name: "Midnight Blue",
    description: "Deep blue tones for focused work",
    category: "dark",
    tags: ["dark", "blue", "professional"],
    colors: {
      "--background": "#0f172a",
      "--foreground": "#e2e8f0",
      "--card": "#1e293b",
      "--card-foreground": "#e2e8f0",
      "--popover": "#1e293b",
      "--popover-foreground": "#e2e8f0",
      "--primary": "#3b82f6",
      "--primary-foreground": "#f8fafc",
      "--secondary": "#334155",
      "--secondary-foreground": "#e2e8f0",
      "--muted": "#1e293b",
      "--muted-foreground": "#94a3b8",
      "--accent": "#2563eb",
      "--accent-foreground": "#f8fafc",
      "--destructive": "#dc2626",
      "--destructive-foreground": "#fef2f2",
      "--border": "#334155",
      "--input": "#1e293b",
      "--ring": "#3b82f6",
    },
  },
  {
    name: "Forest Green",
    description: "Nature-inspired green theme",
    category: "colorful",
    tags: ["dark", "green", "nature"],
    colors: {
      "--background": "#0f1e13",
      "--foreground": "#e7f5ec",
      "--card": "#1a2e20",
      "--card-foreground": "#e7f5ec",
      "--popover": "#1a2e20",
      "--popover-foreground": "#e7f5ec",
      "--primary": "#22c55e",
      "--primary-foreground": "#052e16",
      "--secondary": "#14532d",
      "--secondary-foreground": "#dcfce7",
      "--muted": "#1a2e20",
      "--muted-foreground": "#86efac",
      "--accent": "#16a34a",
      "--accent-foreground": "#f0fdf4",
      "--destructive": "#dc2626",
      "--destructive-foreground": "#fef2f2",
      "--border": "#14532d",
      "--input": "#1a2e20",
      "--ring": "#22c55e",
    },
  },
  {
    name: "High Contrast",
    description: "Maximum accessibility with WCAG AAA contrast",
    category: "accessibility",
    tags: ["dark", "accessibility", "high-contrast"],
    colors: {
      "--background": "#000000",
      "--foreground": "#ffffff",
      "--card": "#000000",
      "--card-foreground": "#ffffff",
      "--popover": "#000000",
      "--popover-foreground": "#ffffff",
      "--primary": "#ffff00",
      "--primary-foreground": "#000000",
      "--secondary": "#1a1a1a",
      "--secondary-foreground": "#ffffff",
      "--muted": "#2a2a2a",
      "--muted-foreground": "#ffffff",
      "--accent": "#00ffff",
      "--accent-foreground": "#000000",
      "--destructive": "#ff0000",
      "--destructive-foreground": "#ffffff",
      "--border": "#ffffff",
      "--input": "#1a1a1a",
      "--ring": "#ffff00",
    },
  },
  {
    name: "Solarized Dark",
    description: "Popular developer theme with reduced blue light",
    category: "dark",
    tags: ["dark", "developer", "solarized"],
    colors: {
      "--background": "#002b36",
      "--foreground": "#839496",
      "--card": "#073642",
      "--card-foreground": "#839496",
      "--popover": "#073642",
      "--popover-foreground": "#839496",
      "--primary": "#268bd2",
      "--primary-foreground": "#fdf6e3",
      "--secondary": "#073642",
      "--secondary-foreground": "#93a1a1",
      "--muted": "#073642",
      "--muted-foreground": "#657b83",
      "--accent": "#2aa198",
      "--accent-foreground": "#fdf6e3",
      "--destructive": "#dc322f",
      "--destructive-foreground": "#fdf6e3",
      "--border": "#073642",
      "--input": "#073642",
      "--ring": "#268bd2",
    },
  },
  {
    name: "Nord",
    description: "Arctic-inspired color palette",
    category: "dark",
    tags: ["dark", "cold", "nordic"],
    colors: {
      "--background": "#2e3440",
      "--foreground": "#eceff4",
      "--card": "#3b4252",
      "--card-foreground": "#eceff4",
      "--popover": "#3b4252",
      "--popover-foreground": "#eceff4",
      "--primary": "#88c0d0",
      "--primary-foreground": "#2e3440",
      "--secondary": "#4c566a",
      "--secondary-foreground": "#eceff4",
      "--muted": "#3b4252",
      "--muted-foreground": "#d8dee9",
      "--accent": "#81a1c1",
      "--accent-foreground": "#eceff4",
      "--destructive": "#bf616a",
      "--destructive-foreground": "#eceff4",
      "--border": "#4c566a",
      "--input": "#3b4252",
      "--ring": "#88c0d0",
    },
  },
];
